[preface]
:source-highlighter: rouge
:icons: font

== Preface

=== Why another book about DSLs in Kotlin?

Kotlin is very suitable to write DSLs and accordingly there exists already a lot of literature about the topic. However, in my opinion many existing books fall short in two ways:

* They focus too much on "toy examples" that give little insight in the process of writing DSLs in practice
* They present solutions in a "vacuum", without highlighting how an effective  design process looks like, which requirements, constraints and limitations apply, and which trade-offs were made

This book tries to address these gaps. It contains a check-list of requirements, which includes less obvious, but nevertheless important aspects. It further shows, how designing DSLs can be structured. Further, the presented DSLs progress from "boring" default examples to more and more challenging and unwieldy cases, and culminate in a discussion of some complex and successful real world DSLs.

Another goal of this book is to avoid presenting DSLs as isolated case studies, but to attempt a classification of DLS. Like design patterns established a common language for field-tested coding solutions, there should be a widely accepted  terminology for classifying DSLs as well, and this book wants to contribute to this effort.

=== Who shouldn't read this book (yet)?

Writing DSLs can be challenging, usually it isn't a good introduction to a host language. That's why this book assumes that you are already somewhat familiar with Kotlin, and - to a lesser degree - with Java.

There _is_ actually a chapter describing many language features of Kotlin, but it is focussing on their possible use in DSLs - so again, this won't be enough to learn the language.

So, if you don't feel comfortable in Kotlin yet, take your time and explore the language first, it will save you from a lot of confusion. This book won't go anywhere in the meantime, it can wait until you can get the most out of it.

=== Prerequisites

To try out code samples from this book or the associated project https://github.com/creativeDsls[], you can use any IDE capable of running Kotlin (obviously IntelliJ IDEA will have an edge regarding Kotlin support), or you can go to https://play.kotlinlang.org/[] for an online sandbox. The Kotlin language version used is 1.7. If not stated otherwise, when discussing Java, language level 11 is assumed.

=== Typographical Conventions

This book uses a few typographical conventions to structure its content.

Inlined code snippets are shown like this: `val answer = 42`

Tips, warnings etc. are shown as follows:

TIP: When the white frost comes, do not eat the yellow snow.

WARNING: First of all, keep him out of the light, he hates bright light, especially sunlight, it’ll kill him. Second, don’t give him any water, not even to drink. But the most important rule, the rule you can never forget, no matter how much he cries, no matter how much he begs, never feed him after midnight.

Example code is shown like this, and may include the file name or lines with numbered remarks:

[source,kotlin]
.src/main/kotlin/personDemo/Person.kt
----
import java.time.ZonedDateTime
import java.time.temporal.ChronoUnit.YEARS

data class Person(val firstName: String, val lastName: String, val age: Int) {<1>
   constructor(firstName: String, lastName: String, dateOfBirth: ZonedDateTime):<2>
       this(firstName, lastName, YEARS.between(dateOfBirth, ZonedDateTime.now()).toInt())
}
----
<1> This is the *main constructor*. For data classes, it also describes the structure of the object and its `toString()` representation.
<2> *Secondary constructors* allow to initialize the object in other ways, however they must delegate to the main constructor.

Additional information may be presented as a sidebar:

.The name "Kotlin"
****
"Kotlin" is a small Russian island in the Baltic Sea. Naming languages or projects after islands has been a tradition in the Java ecosystem. Beside Java itself, there exists e.g. project Lombok, and the Ceylon language.
****

Quotes look like this:

"Code is like humor. When you have to explain it, it’s bad."
-- Cory House

=== Feedback

I'm always thankful for feedback from my readers. Constructive criticism helps to improve this book. As every book, it contains mistakes, omissions, unclear formulations and - as I'm painfully aware as a non-native speaker - bad grammar.

[.text-left]
To send me feedback, e-mail me at feedback@creativedsls.com.
